name: ESLint

on:
  push:
    branches: [ "main" ]
    paths:
      - 'mvc-frontend/**/*'
      - 'react-frontend/**/*'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'mvc-frontend/**/*'
      - 'react-frontend/**/*'
  schedule:
    - cron: '43 2 * * 2'

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Run ESLint on specific folders
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: |
          npx eslint 'mvc-frontend/**/*' \
            'react-frontend/**/*' \
            --config .eslintrc.js \
            --ext .js,.jsx,.ts,.tsx \
            --format @microsoft/eslint-formatter-sarif \
            --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
