name: Vercel React Frontend Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'react-frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Deploy React Frontend to Vercel Production
        uses: amondnet/vercel-action@v41.1.4
        with:
            vercel-token: ${{ secrets.VERCEL_ACCESS_TOKEN }}
            vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
            vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
            working-directory: ./react-frontend/src
            vercel-args: '--prod'

